### PR TITLE
Polishing of the UI/UX

### PR DESCRIPTION
**Pull request by AlinaStepanova**
**Updates:**
1. Created a menu on a toolbar. As far as there is only one primary action - to open a file, so the "Open" button will be always visible to the user. Some extra actions like showing some licenses I assumed as a secondary, so it is better to hide them on the menu, therefore there is more space for the actual content.
2. Added so-called 'null' state when there was nothing selected yet, so it is better to show some icon than empty fields.
3. Disabled EditTexts to be editable. I am not sure what was your primary idea, maybe they should remain editable so, it is up to you what to do =).
4. Updated styling. 
5. Enabled only portrait orientation. As far as activity is getting recreated each time the device is rotated (https://developer.android.com/guide/topics/resources/runtime-changes) and there is no implementation to preserve the state yet in the app, I thought it would be better to use only portrait mode than lose data.
6. Small refactor.

Hope, some of my suggestion will be useful #3 =)

### CODE REVIEW

**Comment by bacloud14** [comment]
What can I say, this is tremendous and seems a whole new release for me. I thank you a lot @AlinaStepanova 
I am excited to test this today later. 

Many thanks ! 
Feel free to add some reference if you want to in UI, it does not bother, because I truly feel you deserve this, like a sample sentence saying "designed by.." or something, If not, I will surely give reference in Play store presentation page in case you want to.

**Comment by bacloud14** [comment]
And I get and agree on all propositions

**Comment by bacloud14** [comment]
This is just fantastic, thanks a lot,

**Comment by bacloud14** [comment]
For
Disabled EditTexts to be editable, I agree but definitely Copyable is better.

**Comment by AlinaStepanova** [comment]
Hi @bacloud14! 
I am glad the changes I have made are useful :)
Also, it would be cool if you can provide some references in a Play Store, but it is not mandatory and completely up to you.
Good luck and happy coding!

**Comment by bacloud14** [comment]
Sure. I put your GitHub in the update presentation. And I will do it in the first app presentation.

**Pull request merged**
